### ISSUE TITLE
Can I use this plugin to call `createClient`

### ISSUE THREAD

**Issue by vedant14** [gatsby-uc/gatsby-source-supabase#1]
I want to use the supabase functionality to do authentication.
The tutorial on supabase site was for react, I thought it could directly work for gatsby as well. But I believe the npm package  `@supabase/supabase-js`, does not work for a gatsby project. 

I realise this issue might be unrelated to the project, but wanted to check if you could provide a solution. Thanks.

**Comment by alan2207** [comment]
Hi @vedant14! Can you tell me more about your use case and what you have tried so far?

**Comment by vedant14** [comment]
Hi @alan2207 , I want to use auth capability provided by Supabase. I tried using their official npm package to enable that. But like I mentioned, that specific npm package caused error while running the build command.

**Comment by alan2207** [comment]
Hi @vedant14 , are your routes client only? Check this out:
https://www.gatsbyjs.com/docs/how-to/routing/client-only-routes-and-user-authentication/

**Comment by moonmeister** [comment]
Thanks for your interest in this project. This plugin is moving into the [Gatsby User Collective](https://github.com/gatsby-uc/plugins) and this repo will be archived. Please open an [issue](https://github.com/gatsby-uc/plugins/issues/new/choose) in that repository, submit a PR if you'd like to see this implemented, or Join us on [Discord](discord.gg/gwnqfzetjv) if you have questions!
