### ISSUE TITLE
Race condition while building for dev

### ISSUE THREAD

**Issue by tacosjs** [gatsby-uc/gatsby-source-supabase#2]
I just turn to supabase for my project and try the package. It seems like sometime (it depends) some of my infos are missing. Let me explain in example:

``` gatsby-config.js
{
      resolve: `gatsby-source-supabase`,
      options: {
        supabaseUrl: process.env.SUPABASE_URL,
        supabaseKey: process.env.SUPABASE_KEY,
        types: [
          {
            type: "Review",
            query: (client) => client.from("review").select("*"),
          },
        ],
      },
    },
```

While in http://localhost:8000/___graphql  sometime I can see the query 
```
{
  allReview {
    edges {
      node {
        id
      }
    }
  }
}
```

but while in template, sometime (not happen all times!) graphql query return an error `Cannot query field "allReview" on type "Query".`

Edit: It seems like thing appear and disappear randomly while restarting the build (event with a clean)

**Comment by malitov** [comment]
@jslyonnais The issue is in the supabase query. Should be use with async/await

**Comment by moonmeister** [comment]
Thanks for your interest in this project. This plugin is moving into the [Gatsby User Collective](https://github.com/gatsby-uc/plugins) and this repo will be archived. Please open an [issue](https://github.com/gatsby-uc/plugins/issues/new/choose) in that repository, submit a PR if you'd like to see this implemented, or Join us on [Discord](discord.gg/gwnqfzetjv) if you have questions!
