### ISSUE TITLE
Moving Plugin to the Gatsby User Collective 

### ISSUE THREAD

**Issue by moonmeister** [gatsby-uc/gatsby-source-supabase#3]
Hello @alan2207, thanks for your work starting this plugin! I help run the [Gatsby User Collective](https://github.com/gatsby-uc/plugins) where the Gatsby community can work together to help maintain plugins. I'd love to see this plugin moved into the collective! Somewhat selfishly cause I use it and want to make some improvements! I'm also happy to contribute here if you're able to merge and release PRs. 

If you are interested in contributing the plugin we have some docs on that very matter: https://github.com/gatsby-uc/plugins/blob/main/CONTRIBUTING.md#contributing-a-plugin. Please let me know if you have any further questions!

**Comment by alan2207** [comment]
Hey @moonmeister , this is a great initiative. I haven't had much time lately to maintain the plugin, so I would gladly move it to the collective. I took a look at the guide, just want to check if I got it correctly:

1. I add you as a maintainer to npm for this package
2. Then I adjust the source code to match the plugins repo
3. I add the package to the plugins repo and create a PR

Is there anything else I missed that is required?

**Comment by moonmeister** [comment]
#1 is most important. 

I also like to have this repo transferred to the organization . 

Once those things are done you or I can do the work to get it into the monorepo and merged in.

**Comment by moonmeister** [comment]
Also, let's get an issue open for submitting a plugin and we can work from there

**Comment by alan2207** [comment]
Done. I added you as a maintainer to npm. Let me know if there is anything else I can do.

**Comment by moonmeister** [comment]
Thanks
